import js from "@eslint/js";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import reactX from "eslint-plugin-react-x";
import reactDom from "eslint-plugin-react-dom";
import tseslint from "typescript-eslint";
import { defineConfig, globalIgnores } from "eslint/config";

export default defineConfig([
    globalIgnores([
        "dist",
        "worker-configuration.d.ts",
        // Auto-generated by @hey-api/openapi-ts (see openapi-ts.config.ts).
        "onshape-api-reference"
    ]),
    {
        files: ["**/*.{ts,tsx}"],
        extends: [
            js.configs.recommended,
            tseslint.configs.recommendedTypeChecked,
            tseslint.configs.stylisticTypeChecked,
            reactHooks.configs.flat.recommended,
            reactRefresh.configs.vite,
            reactX.configs["recommended-typescript"],
            reactDom.configs.recommended
        ],
        rules: {
            // Two import statements for one module drift apart; a dozen pairs
            // had accumulated. A namespace import is not reported, so the
            // `import * as` a test spies through still stands beside its named one.
            "no-duplicate-imports": "error",

            // tsc has no deprecation check — @deprecated is an editor-only hint,
            // so lint is the only thing that fails a build on one.
            "@typescript-eslint/no-deprecated": "error",

            // TanStack Router files must export both component and route config object
            "react-refresh/only-export-components": "off",

            // `!x || x.y` is the preferred style in this codebase over optional chaining
            "@typescript-eslint/prefer-optional-chain": "off",

            // throw redirect() is idiomatic TanStack Router — not an Error, but intentional
            "@typescript-eslint/only-throw-error": "off",

            // prefer `if (!x)` over `??=` — style preference
            "@typescript-eslint/prefer-nullish-coalescing": "off"
        },
        languageOptions: {
            globals: globals.browser,
            parserOptions: {
                projectService: {
                    allowDefaultProject: [
                        "drizzle.config.ts",
                        "openapi-ts.config.ts",
                        "worker-configuration.d.ts"
                    ]
                },
                tsconfigRootDir: import.meta.dirname
            }
        }
    },
    {
        // The enum rules catch a comparison between two different enums. What
        // fires here is a string or a number compared against the enum it is
        // spelled as — an HTTP status, a library id out of a route param — which
        // is the comparison being asked for, not a mistake.
        files: ["**/*.{ts,tsx}"],
        rules: { "@typescript-eslint/no-unsafe-enum-comparison": "off" }
    },
    {
        // Vitest's asymmetric matchers are typed `any`, so an object built
        // around one is unsafe by construction and by nobody's fault.
        files: ["**/*.test.{ts,tsx}"],
        rules: { "@typescript-eslint/no-unsafe-assignment": "off" }
    },
    {
        // Build configuration, which walks Onshape's OpenAPI document and reads
        // an environment this project's tsconfigs do not describe.
        files: ["*.config.ts"],
        rules: {
            "@typescript-eslint/no-explicit-any": "off",
            "@typescript-eslint/no-unsafe-assignment": "off",
            "@typescript-eslint/no-unsafe-member-access": "off",
            "@typescript-eslint/no-unsafe-return": "off",
            "@typescript-eslint/no-unsafe-argument": "off",
            "@typescript-eslint/no-unsafe-call": "off"
        }
    },
    {
        // Onshape's API is untyped, and typing the whole of it is not on the
        // cards, so `any` flows out of the client and through whatever parses
        // its responses. Scoped here rather than switched off everywhere: the
        // frontend and the features have contracts of their own, and should be
        // told when an `any` reaches them.
        files: [
            "src/backend/lib/onshape/**/*.ts",
            "src/backend/features/load/**/*.ts",
            "src/backend/features/configurations/input-parser.ts"
        ],
        rules: {
            "@typescript-eslint/no-explicit-any": "off",
            "@typescript-eslint/no-unsafe-assignment": "off",
            "@typescript-eslint/no-unsafe-member-access": "off",
            "@typescript-eslint/no-unsafe-return": "off",
            "@typescript-eslint/no-unsafe-argument": "off",
            "@typescript-eslint/no-unsafe-call": "off",
            "@typescript-eslint/no-unsafe-enum-comparison": "off"
        }
    }
]);
