/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as PagesSafariErrorRouteImport } from './routes/_pages/safari-error'
import { Route as PagesLicenseRouteImport } from './routes/_pages/license'
import { Route as PagesGrantDeniedRouteImport } from './routes/_pages/grant-denied'
import { Route as PagesCookieErrorRouteImport } from './routes/_pages/cookie-error'
import { Route as PagesBetaCompleteRouteImport } from './routes/_pages/beta-complete'
import { Route as AppDocumentsIndexRouteImport } from './routes/app/documents/index'
import { Route as AppDocumentsDocumentIdRouteImport } from './routes/app/documents/$documentId'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesSafariErrorRoute = PagesSafariErrorRouteImport.update({
  id: '/_pages/safari-error',
  path: '/safari-error',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesLicenseRoute = PagesLicenseRouteImport.update({
  id: '/_pages/license',
  path: '/license',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesGrantDeniedRoute = PagesGrantDeniedRouteImport.update({
  id: '/_pages/grant-denied',
  path: '/grant-denied',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesCookieErrorRoute = PagesCookieErrorRouteImport.update({
  id: '/_pages/cookie-error',
  path: '/cookie-error',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesBetaCompleteRoute = PagesBetaCompleteRouteImport.update({
  id: '/_pages/beta-complete',
  path: '/beta-complete',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDocumentsIndexRoute = AppDocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDocumentsDocumentIdRoute = AppDocumentsDocumentIdRouteImport.update({
  id: '/documents/$documentId',
  path: '/documents/$documentId',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/beta-complete': typeof PagesBetaCompleteRoute
  '/cookie-error': typeof PagesCookieErrorRoute
  '/grant-denied': typeof PagesGrantDeniedRoute
  '/license': typeof PagesLicenseRoute
  '/safari-error': typeof PagesSafariErrorRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/app/documents/$documentId': typeof AppDocumentsDocumentIdRoute
  '/app/documents/': typeof AppDocumentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/beta-complete': typeof PagesBetaCompleteRoute
  '/cookie-error': typeof PagesCookieErrorRoute
  '/grant-denied': typeof PagesGrantDeniedRoute
  '/license': typeof PagesLicenseRoute
  '/safari-error': typeof PagesSafariErrorRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/app/documents/$documentId': typeof AppDocumentsDocumentIdRoute
  '/app/documents': typeof AppDocumentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/_pages/beta-complete': typeof PagesBetaCompleteRoute
  '/_pages/cookie-error': typeof PagesCookieErrorRoute
  '/_pages/grant-denied': typeof PagesGrantDeniedRoute
  '/_pages/license': typeof PagesLicenseRoute
  '/_pages/safari-error': typeof PagesSafariErrorRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/app/documents/$documentId': typeof AppDocumentsDocumentIdRoute
  '/app/documents/': typeof AppDocumentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/beta-complete'
    | '/cookie-error'
    | '/grant-denied'
    | '/license'
    | '/safari-error'
    | '/auth/callback'
    | '/auth/sign-in'
    | '/app/documents/$documentId'
    | '/app/documents/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/beta-complete'
    | '/cookie-error'
    | '/grant-denied'
    | '/license'
    | '/safari-error'
    | '/auth/callback'
    | '/auth/sign-in'
    | '/app/documents/$documentId'
    | '/app/documents'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/_pages/beta-complete'
    | '/_pages/cookie-error'
    | '/_pages/grant-denied'
    | '/_pages/license'
    | '/_pages/safari-error'
    | '/auth/callback'
    | '/auth/sign-in'
    | '/app/documents/$documentId'
    | '/app/documents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  PagesBetaCompleteRoute: typeof PagesBetaCompleteRoute
  PagesCookieErrorRoute: typeof PagesCookieErrorRoute
  PagesGrantDeniedRoute: typeof PagesGrantDeniedRoute
  PagesLicenseRoute: typeof PagesLicenseRoute
  PagesSafariErrorRoute: typeof PagesSafariErrorRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthSignInRoute: typeof AuthSignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pages/safari-error': {
      id: '/_pages/safari-error'
      path: '/safari-error'
      fullPath: '/safari-error'
      preLoaderRoute: typeof PagesSafariErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pages/license': {
      id: '/_pages/license'
      path: '/license'
      fullPath: '/license'
      preLoaderRoute: typeof PagesLicenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pages/grant-denied': {
      id: '/_pages/grant-denied'
      path: '/grant-denied'
      fullPath: '/grant-denied'
      preLoaderRoute: typeof PagesGrantDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pages/cookie-error': {
      id: '/_pages/cookie-error'
      path: '/cookie-error'
      fullPath: '/cookie-error'
      preLoaderRoute: typeof PagesCookieErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pages/beta-complete': {
      id: '/_pages/beta-complete'
      path: '/beta-complete'
      fullPath: '/beta-complete'
      preLoaderRoute: typeof PagesBetaCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/documents/': {
      id: '/app/documents/'
      path: '/documents'
      fullPath: '/app/documents/'
      preLoaderRoute: typeof AppDocumentsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/documents/$documentId': {
      id: '/app/documents/$documentId'
      path: '/documents/$documentId'
      fullPath: '/app/documents/$documentId'
      preLoaderRoute: typeof AppDocumentsDocumentIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppDocumentsDocumentIdRoute: typeof AppDocumentsDocumentIdRoute
  AppDocumentsIndexRoute: typeof AppDocumentsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDocumentsDocumentIdRoute: AppDocumentsDocumentIdRoute,
  AppDocumentsIndexRoute: AppDocumentsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  PagesBetaCompleteRoute: PagesBetaCompleteRoute,
  PagesCookieErrorRoute: PagesCookieErrorRoute,
  PagesGrantDeniedRoute: PagesGrantDeniedRoute,
  PagesLicenseRoute: PagesLicenseRoute,
  PagesSafariErrorRoute: PagesSafariErrorRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthSignInRoute: AuthSignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router'
import type { startInstance } from './start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
