/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AppVersionManagerRouteImport } from './routes/app/version-manager'
import { Route as PagesVersionErrorRouteImport } from './routes/_pages/version-error'
import { Route as PagesSetupRouteImport } from './routes/_pages/setup'
import { Route as PagesSafariErrorRouteImport } from './routes/_pages/safari-error'
import { Route as PagesLicenseRouteImport } from './routes/_pages/license'
import { Route as PagesGrantDeniedRouteImport } from './routes/_pages/grant-denied'
import { Route as PagesCookieErrorRouteImport } from './routes/_pages/cookie-error'
import { Route as PagesBetaCompleteRouteImport } from './routes/_pages/beta-complete'
import { Route as DashboardLibraryLibraryIdRouteRouteImport } from './routes/dashboard/library/$libraryId/route'
import { Route as AppLibraryLibraryIdRouteRouteImport } from './routes/app/library/$libraryId/route'
import { Route as DashboardLibraryLibraryIdIndexRouteImport } from './routes/dashboard/library/$libraryId/index'
import { Route as AppLibraryLibraryIdIndexRouteImport } from './routes/app/library/$libraryId/index'
import { Route as DashboardLibraryLibraryIdUnusedRouteImport } from './routes/dashboard/library/$libraryId/unused'
import { Route as DashboardLibraryLibraryIdPartRouteImport } from './routes/dashboard/library/$libraryId/part'
import { Route as AppLibraryLibraryIdGroupsGroupIdRouteImport } from './routes/app/library/$libraryId/groups/$groupId'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AppVersionManagerRoute = AppVersionManagerRouteImport.update({
  id: '/version-manager',
  path: '/version-manager',
  getParentRoute: () => AppRouteRoute,
} as any)
const PagesVersionErrorRoute = PagesVersionErrorRouteImport.update({
  id: '/_pages/version-error',
  path: '/version-error',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesSetupRoute = PagesSetupRouteImport.update({
  id: '/_pages/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesSafariErrorRoute = PagesSafariErrorRouteImport.update({
  id: '/_pages/safari-error',
  path: '/safari-error',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesLicenseRoute = PagesLicenseRouteImport.update({
  id: '/_pages/license',
  path: '/license',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesGrantDeniedRoute = PagesGrantDeniedRouteImport.update({
  id: '/_pages/grant-denied',
  path: '/grant-denied',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesCookieErrorRoute = PagesCookieErrorRouteImport.update({
  id: '/_pages/cookie-error',
  path: '/cookie-error',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesBetaCompleteRoute = PagesBetaCompleteRouteImport.update({
  id: '/_pages/beta-complete',
  path: '/beta-complete',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLibraryLibraryIdRouteRoute =
  DashboardLibraryLibraryIdRouteRouteImport.update({
    id: '/library/$libraryId',
    path: '/library/$libraryId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const AppLibraryLibraryIdRouteRoute =
  AppLibraryLibraryIdRouteRouteImport.update({
    id: '/library/$libraryId',
    path: '/library/$libraryId',
    getParentRoute: () => AppRouteRoute,
  } as any)
const DashboardLibraryLibraryIdIndexRoute =
  DashboardLibraryLibraryIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardLibraryLibraryIdRouteRoute,
  } as any)
const AppLibraryLibraryIdIndexRoute =
  AppLibraryLibraryIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppLibraryLibraryIdRouteRoute,
  } as any)
const DashboardLibraryLibraryIdUnusedRoute =
  DashboardLibraryLibraryIdUnusedRouteImport.update({
    id: '/unused',
    path: '/unused',
    getParentRoute: () => DashboardLibraryLibraryIdRouteRoute,
  } as any)
const DashboardLibraryLibraryIdPartRoute =
  DashboardLibraryLibraryIdPartRouteImport.update({
    id: '/part',
    path: '/part',
    getParentRoute: () => DashboardLibraryLibraryIdRouteRoute,
  } as any)
const AppLibraryLibraryIdGroupsGroupIdRoute =
  AppLibraryLibraryIdGroupsGroupIdRouteImport.update({
    id: '/groups/$groupId',
    path: '/groups/$groupId',
    getParentRoute: () => AppLibraryLibraryIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/beta-complete': typeof PagesBetaCompleteRoute
  '/cookie-error': typeof PagesCookieErrorRoute
  '/grant-denied': typeof PagesGrantDeniedRoute
  '/license': typeof PagesLicenseRoute
  '/safari-error': typeof PagesSafariErrorRoute
  '/setup': typeof PagesSetupRoute
  '/version-error': typeof PagesVersionErrorRoute
  '/app/version-manager': typeof AppVersionManagerRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/app/library/$libraryId': typeof AppLibraryLibraryIdRouteRouteWithChildren
  '/dashboard/library/$libraryId': typeof DashboardLibraryLibraryIdRouteRouteWithChildren
  '/dashboard/library/$libraryId/part': typeof DashboardLibraryLibraryIdPartRoute
  '/dashboard/library/$libraryId/unused': typeof DashboardLibraryLibraryIdUnusedRoute
  '/app/library/$libraryId/': typeof AppLibraryLibraryIdIndexRoute
  '/dashboard/library/$libraryId/': typeof DashboardLibraryLibraryIdIndexRoute
  '/app/library/$libraryId/groups/$groupId': typeof AppLibraryLibraryIdGroupsGroupIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/beta-complete': typeof PagesBetaCompleteRoute
  '/cookie-error': typeof PagesCookieErrorRoute
  '/grant-denied': typeof PagesGrantDeniedRoute
  '/license': typeof PagesLicenseRoute
  '/safari-error': typeof PagesSafariErrorRoute
  '/setup': typeof PagesSetupRoute
  '/version-error': typeof PagesVersionErrorRoute
  '/app/version-manager': typeof AppVersionManagerRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/library/$libraryId/part': typeof DashboardLibraryLibraryIdPartRoute
  '/dashboard/library/$libraryId/unused': typeof DashboardLibraryLibraryIdUnusedRoute
  '/app/library/$libraryId': typeof AppLibraryLibraryIdIndexRoute
  '/dashboard/library/$libraryId': typeof DashboardLibraryLibraryIdIndexRoute
  '/app/library/$libraryId/groups/$groupId': typeof AppLibraryLibraryIdGroupsGroupIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/_pages/beta-complete': typeof PagesBetaCompleteRoute
  '/_pages/cookie-error': typeof PagesCookieErrorRoute
  '/_pages/grant-denied': typeof PagesGrantDeniedRoute
  '/_pages/license': typeof PagesLicenseRoute
  '/_pages/safari-error': typeof PagesSafariErrorRoute
  '/_pages/setup': typeof PagesSetupRoute
  '/_pages/version-error': typeof PagesVersionErrorRoute
  '/app/version-manager': typeof AppVersionManagerRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/app/library/$libraryId': typeof AppLibraryLibraryIdRouteRouteWithChildren
  '/dashboard/library/$libraryId': typeof DashboardLibraryLibraryIdRouteRouteWithChildren
  '/dashboard/library/$libraryId/part': typeof DashboardLibraryLibraryIdPartRoute
  '/dashboard/library/$libraryId/unused': typeof DashboardLibraryLibraryIdUnusedRoute
  '/app/library/$libraryId/': typeof AppLibraryLibraryIdIndexRoute
  '/dashboard/library/$libraryId/': typeof DashboardLibraryLibraryIdIndexRoute
  '/app/library/$libraryId/groups/$groupId': typeof AppLibraryLibraryIdGroupsGroupIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/dashboard'
    | '/beta-complete'
    | '/cookie-error'
    | '/grant-denied'
    | '/license'
    | '/safari-error'
    | '/setup'
    | '/version-error'
    | '/app/version-manager'
    | '/dashboard/'
    | '/app/library/$libraryId'
    | '/dashboard/library/$libraryId'
    | '/dashboard/library/$libraryId/part'
    | '/dashboard/library/$libraryId/unused'
    | '/app/library/$libraryId/'
    | '/dashboard/library/$libraryId/'
    | '/app/library/$libraryId/groups/$groupId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/beta-complete'
    | '/cookie-error'
    | '/grant-denied'
    | '/license'
    | '/safari-error'
    | '/setup'
    | '/version-error'
    | '/app/version-manager'
    | '/dashboard'
    | '/dashboard/library/$libraryId/part'
    | '/dashboard/library/$libraryId/unused'
    | '/app/library/$libraryId'
    | '/dashboard/library/$libraryId'
    | '/app/library/$libraryId/groups/$groupId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/dashboard'
    | '/_pages/beta-complete'
    | '/_pages/cookie-error'
    | '/_pages/grant-denied'
    | '/_pages/license'
    | '/_pages/safari-error'
    | '/_pages/setup'
    | '/_pages/version-error'
    | '/app/version-manager'
    | '/dashboard/'
    | '/app/library/$libraryId'
    | '/dashboard/library/$libraryId'
    | '/dashboard/library/$libraryId/part'
    | '/dashboard/library/$libraryId/unused'
    | '/app/library/$libraryId/'
    | '/dashboard/library/$libraryId/'
    | '/app/library/$libraryId/groups/$groupId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  PagesBetaCompleteRoute: typeof PagesBetaCompleteRoute
  PagesCookieErrorRoute: typeof PagesCookieErrorRoute
  PagesGrantDeniedRoute: typeof PagesGrantDeniedRoute
  PagesLicenseRoute: typeof PagesLicenseRoute
  PagesSafariErrorRoute: typeof PagesSafariErrorRoute
  PagesSetupRoute: typeof PagesSetupRoute
  PagesVersionErrorRoute: typeof PagesVersionErrorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/app/version-manager': {
      id: '/app/version-manager'
      path: '/version-manager'
      fullPath: '/app/version-manager'
      preLoaderRoute: typeof AppVersionManagerRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_pages/version-error': {
      id: '/_pages/version-error'
      path: '/version-error'
      fullPath: '/version-error'
      preLoaderRoute: typeof PagesVersionErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pages/setup': {
      id: '/_pages/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof PagesSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pages/safari-error': {
      id: '/_pages/safari-error'
      path: '/safari-error'
      fullPath: '/safari-error'
      preLoaderRoute: typeof PagesSafariErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pages/license': {
      id: '/_pages/license'
      path: '/license'
      fullPath: '/license'
      preLoaderRoute: typeof PagesLicenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pages/grant-denied': {
      id: '/_pages/grant-denied'
      path: '/grant-denied'
      fullPath: '/grant-denied'
      preLoaderRoute: typeof PagesGrantDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pages/cookie-error': {
      id: '/_pages/cookie-error'
      path: '/cookie-error'
      fullPath: '/cookie-error'
      preLoaderRoute: typeof PagesCookieErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pages/beta-complete': {
      id: '/_pages/beta-complete'
      path: '/beta-complete'
      fullPath: '/beta-complete'
      preLoaderRoute: typeof PagesBetaCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/library/$libraryId': {
      id: '/dashboard/library/$libraryId'
      path: '/library/$libraryId'
      fullPath: '/dashboard/library/$libraryId'
      preLoaderRoute: typeof DashboardLibraryLibraryIdRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/app/library/$libraryId': {
      id: '/app/library/$libraryId'
      path: '/library/$libraryId'
      fullPath: '/app/library/$libraryId'
      preLoaderRoute: typeof AppLibraryLibraryIdRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/dashboard/library/$libraryId/': {
      id: '/dashboard/library/$libraryId/'
      path: '/'
      fullPath: '/dashboard/library/$libraryId/'
      preLoaderRoute: typeof DashboardLibraryLibraryIdIndexRouteImport
      parentRoute: typeof DashboardLibraryLibraryIdRouteRoute
    }
    '/app/library/$libraryId/': {
      id: '/app/library/$libraryId/'
      path: '/'
      fullPath: '/app/library/$libraryId/'
      preLoaderRoute: typeof AppLibraryLibraryIdIndexRouteImport
      parentRoute: typeof AppLibraryLibraryIdRouteRoute
    }
    '/dashboard/library/$libraryId/unused': {
      id: '/dashboard/library/$libraryId/unused'
      path: '/unused'
      fullPath: '/dashboard/library/$libraryId/unused'
      preLoaderRoute: typeof DashboardLibraryLibraryIdUnusedRouteImport
      parentRoute: typeof DashboardLibraryLibraryIdRouteRoute
    }
    '/dashboard/library/$libraryId/part': {
      id: '/dashboard/library/$libraryId/part'
      path: '/part'
      fullPath: '/dashboard/library/$libraryId/part'
      preLoaderRoute: typeof DashboardLibraryLibraryIdPartRouteImport
      parentRoute: typeof DashboardLibraryLibraryIdRouteRoute
    }
    '/app/library/$libraryId/groups/$groupId': {
      id: '/app/library/$libraryId/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/app/library/$libraryId/groups/$groupId'
      preLoaderRoute: typeof AppLibraryLibraryIdGroupsGroupIdRouteImport
      parentRoute: typeof AppLibraryLibraryIdRouteRoute
    }
  }
}

interface AppLibraryLibraryIdRouteRouteChildren {
  AppLibraryLibraryIdIndexRoute: typeof AppLibraryLibraryIdIndexRoute
  AppLibraryLibraryIdGroupsGroupIdRoute: typeof AppLibraryLibraryIdGroupsGroupIdRoute
}

const AppLibraryLibraryIdRouteRouteChildren: AppLibraryLibraryIdRouteRouteChildren =
  {
    AppLibraryLibraryIdIndexRoute: AppLibraryLibraryIdIndexRoute,
    AppLibraryLibraryIdGroupsGroupIdRoute:
      AppLibraryLibraryIdGroupsGroupIdRoute,
  }

const AppLibraryLibraryIdRouteRouteWithChildren =
  AppLibraryLibraryIdRouteRoute._addFileChildren(
    AppLibraryLibraryIdRouteRouteChildren,
  )

interface AppRouteRouteChildren {
  AppVersionManagerRoute: typeof AppVersionManagerRoute
  AppLibraryLibraryIdRouteRoute: typeof AppLibraryLibraryIdRouteRouteWithChildren
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppVersionManagerRoute: AppVersionManagerRoute,
  AppLibraryLibraryIdRouteRoute: AppLibraryLibraryIdRouteRouteWithChildren,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface DashboardLibraryLibraryIdRouteRouteChildren {
  DashboardLibraryLibraryIdPartRoute: typeof DashboardLibraryLibraryIdPartRoute
  DashboardLibraryLibraryIdUnusedRoute: typeof DashboardLibraryLibraryIdUnusedRoute
  DashboardLibraryLibraryIdIndexRoute: typeof DashboardLibraryLibraryIdIndexRoute
}

const DashboardLibraryLibraryIdRouteRouteChildren: DashboardLibraryLibraryIdRouteRouteChildren =
  {
    DashboardLibraryLibraryIdPartRoute: DashboardLibraryLibraryIdPartRoute,
    DashboardLibraryLibraryIdUnusedRoute: DashboardLibraryLibraryIdUnusedRoute,
    DashboardLibraryLibraryIdIndexRoute: DashboardLibraryLibraryIdIndexRoute,
  }

const DashboardLibraryLibraryIdRouteRouteWithChildren =
  DashboardLibraryLibraryIdRouteRoute._addFileChildren(
    DashboardLibraryLibraryIdRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardLibraryLibraryIdRouteRoute: typeof DashboardLibraryLibraryIdRouteRouteWithChildren
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardLibraryLibraryIdRouteRoute:
    DashboardLibraryLibraryIdRouteRouteWithChildren,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  PagesBetaCompleteRoute: PagesBetaCompleteRoute,
  PagesCookieErrorRoute: PagesCookieErrorRoute,
  PagesGrantDeniedRoute: PagesGrantDeniedRoute,
  PagesLicenseRoute: PagesLicenseRoute,
  PagesSafariErrorRoute: PagesSafariErrorRoute,
  PagesSetupRoute: PagesSetupRoute,
  PagesVersionErrorRoute: PagesVersionErrorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
