/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppDocumentsRouteImport } from './routes/app/documents'
import { Route as PagesSafariErrorRouteImport } from './routes/_pages/safari-error'
import { Route as PagesNotFoundRouteImport } from './routes/_pages/not-found'
import { Route as PagesLicenseRouteImport } from './routes/_pages/license'
import { Route as PagesGrantDeniedRouteImport } from './routes/_pages/grant-denied'
import { Route as PagesCookieErrorRouteImport } from './routes/_pages/cookie-error'
import { Route as PagesBetaCompleteRouteImport } from './routes/_pages/beta-complete'
import { Route as AppDocumentsIndexRouteImport } from './routes/app/documents/index'
import { Route as AppDocumentsDocumentIdRouteImport } from './routes/app/documents/$documentId'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const PagesSafariErrorRoute = PagesSafariErrorRouteImport.update({
  id: '/_pages/safari-error',
  path: '/safari-error',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesNotFoundRoute = PagesNotFoundRouteImport.update({
  id: '/_pages/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesLicenseRoute = PagesLicenseRouteImport.update({
  id: '/_pages/license',
  path: '/license',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesGrantDeniedRoute = PagesGrantDeniedRouteImport.update({
  id: '/_pages/grant-denied',
  path: '/grant-denied',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesCookieErrorRoute = PagesCookieErrorRouteImport.update({
  id: '/_pages/cookie-error',
  path: '/cookie-error',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesBetaCompleteRoute = PagesBetaCompleteRouteImport.update({
  id: '/_pages/beta-complete',
  path: '/beta-complete',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDocumentsIndexRoute = AppDocumentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDocumentsRoute,
} as any)
const AppDocumentsDocumentIdRoute = AppDocumentsDocumentIdRouteImport.update({
  id: '/$documentId',
  path: '/$documentId',
  getParentRoute: () => AppDocumentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/app': typeof AppRouteWithChildren
  '/beta-complete': typeof PagesBetaCompleteRoute
  '/cookie-error': typeof PagesCookieErrorRoute
  '/grant-denied': typeof PagesGrantDeniedRoute
  '/license': typeof PagesLicenseRoute
  '/not-found': typeof PagesNotFoundRoute
  '/safari-error': typeof PagesSafariErrorRoute
  '/app/documents': typeof AppDocumentsRouteWithChildren
  '/app/documents/$documentId': typeof AppDocumentsDocumentIdRoute
  '/app/documents/': typeof AppDocumentsIndexRoute
}
export interface FileRoutesByTo {
  '/app': typeof AppRouteWithChildren
  '/beta-complete': typeof PagesBetaCompleteRoute
  '/cookie-error': typeof PagesCookieErrorRoute
  '/grant-denied': typeof PagesGrantDeniedRoute
  '/license': typeof PagesLicenseRoute
  '/not-found': typeof PagesNotFoundRoute
  '/safari-error': typeof PagesSafariErrorRoute
  '/app/documents/$documentId': typeof AppDocumentsDocumentIdRoute
  '/app/documents': typeof AppDocumentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/app': typeof AppRouteWithChildren
  '/_pages/beta-complete': typeof PagesBetaCompleteRoute
  '/_pages/cookie-error': typeof PagesCookieErrorRoute
  '/_pages/grant-denied': typeof PagesGrantDeniedRoute
  '/_pages/license': typeof PagesLicenseRoute
  '/_pages/not-found': typeof PagesNotFoundRoute
  '/_pages/safari-error': typeof PagesSafariErrorRoute
  '/app/documents': typeof AppDocumentsRouteWithChildren
  '/app/documents/$documentId': typeof AppDocumentsDocumentIdRoute
  '/app/documents/': typeof AppDocumentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/app'
    | '/beta-complete'
    | '/cookie-error'
    | '/grant-denied'
    | '/license'
    | '/not-found'
    | '/safari-error'
    | '/app/documents'
    | '/app/documents/$documentId'
    | '/app/documents/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/app'
    | '/beta-complete'
    | '/cookie-error'
    | '/grant-denied'
    | '/license'
    | '/not-found'
    | '/safari-error'
    | '/app/documents/$documentId'
    | '/app/documents'
  id:
    | '__root__'
    | '/app'
    | '/_pages/beta-complete'
    | '/_pages/cookie-error'
    | '/_pages/grant-denied'
    | '/_pages/license'
    | '/_pages/not-found'
    | '/_pages/safari-error'
    | '/app/documents'
    | '/app/documents/$documentId'
    | '/app/documents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  PagesBetaCompleteRoute: typeof PagesBetaCompleteRoute
  PagesCookieErrorRoute: typeof PagesCookieErrorRoute
  PagesGrantDeniedRoute: typeof PagesGrantDeniedRoute
  PagesLicenseRoute: typeof PagesLicenseRoute
  PagesNotFoundRoute: typeof PagesNotFoundRoute
  PagesSafariErrorRoute: typeof PagesSafariErrorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/documents': {
      id: '/app/documents'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_pages/safari-error': {
      id: '/_pages/safari-error'
      path: '/safari-error'
      fullPath: '/safari-error'
      preLoaderRoute: typeof PagesSafariErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pages/not-found': {
      id: '/_pages/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof PagesNotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pages/license': {
      id: '/_pages/license'
      path: '/license'
      fullPath: '/license'
      preLoaderRoute: typeof PagesLicenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pages/grant-denied': {
      id: '/_pages/grant-denied'
      path: '/grant-denied'
      fullPath: '/grant-denied'
      preLoaderRoute: typeof PagesGrantDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pages/cookie-error': {
      id: '/_pages/cookie-error'
      path: '/cookie-error'
      fullPath: '/cookie-error'
      preLoaderRoute: typeof PagesCookieErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pages/beta-complete': {
      id: '/_pages/beta-complete'
      path: '/beta-complete'
      fullPath: '/beta-complete'
      preLoaderRoute: typeof PagesBetaCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/documents/': {
      id: '/app/documents/'
      path: '/'
      fullPath: '/app/documents/'
      preLoaderRoute: typeof AppDocumentsIndexRouteImport
      parentRoute: typeof AppDocumentsRoute
    }
    '/app/documents/$documentId': {
      id: '/app/documents/$documentId'
      path: '/$documentId'
      fullPath: '/app/documents/$documentId'
      preLoaderRoute: typeof AppDocumentsDocumentIdRouteImport
      parentRoute: typeof AppDocumentsRoute
    }
  }
}

interface AppDocumentsRouteChildren {
  AppDocumentsDocumentIdRoute: typeof AppDocumentsDocumentIdRoute
  AppDocumentsIndexRoute: typeof AppDocumentsIndexRoute
}

const AppDocumentsRouteChildren: AppDocumentsRouteChildren = {
  AppDocumentsDocumentIdRoute: AppDocumentsDocumentIdRoute,
  AppDocumentsIndexRoute: AppDocumentsIndexRoute,
}

const AppDocumentsRouteWithChildren = AppDocumentsRoute._addFileChildren(
  AppDocumentsRouteChildren,
)

interface AppRouteChildren {
  AppDocumentsRoute: typeof AppDocumentsRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppDocumentsRoute: AppDocumentsRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  PagesBetaCompleteRoute: PagesBetaCompleteRoute,
  PagesCookieErrorRoute: PagesCookieErrorRoute,
  PagesGrantDeniedRoute: PagesGrantDeniedRoute,
  PagesLicenseRoute: PagesLicenseRoute,
  PagesNotFoundRoute: PagesNotFoundRoute,
  PagesSafariErrorRoute: PagesSafariErrorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
