/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AppDocumentsRouteImport } from './routes/app/documents'
import { Route as ApiSearchDbRouteImport } from './routes/api/search-db'
import { Route as ApiLibraryDataRouteImport } from './routes/api/library-data'
import { Route as ApiConfigurationRouteImport } from './routes/api/configuration'
import { Route as PagesSafariErrorRouteImport } from './routes/_pages/safari-error'
import { Route as PagesLicenseRouteImport } from './routes/_pages/license'
import { Route as PagesGrantDeniedRouteImport } from './routes/_pages/grant-denied'
import { Route as PagesCookieErrorRouteImport } from './routes/_pages/cookie-error'
import { Route as PagesBetaCompleteRouteImport } from './routes/_pages/beta-complete'
import { Route as AppDocumentsIndexRouteImport } from './routes/app/documents/index'
import { Route as AppDocumentsDocumentIdRouteImport } from './routes/app/documents/$documentId'
import { Route as ApiAdminSearchDbRouteImport } from './routes/api/admin/search-db'
import { Route as ApiAdminLibraryDataRouteImport } from './routes/api/admin/library-data'
import { Route as ApiAdminConfigurationRouteImport } from './routes/api/admin/configuration'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const ApiSearchDbRoute = ApiSearchDbRouteImport.update({
  id: '/api/search-db',
  path: '/api/search-db',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLibraryDataRoute = ApiLibraryDataRouteImport.update({
  id: '/api/library-data',
  path: '/api/library-data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConfigurationRoute = ApiConfigurationRouteImport.update({
  id: '/api/configuration',
  path: '/api/configuration',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesSafariErrorRoute = PagesSafariErrorRouteImport.update({
  id: '/_pages/safari-error',
  path: '/safari-error',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesLicenseRoute = PagesLicenseRouteImport.update({
  id: '/_pages/license',
  path: '/license',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesGrantDeniedRoute = PagesGrantDeniedRouteImport.update({
  id: '/_pages/grant-denied',
  path: '/grant-denied',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesCookieErrorRoute = PagesCookieErrorRouteImport.update({
  id: '/_pages/cookie-error',
  path: '/cookie-error',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesBetaCompleteRoute = PagesBetaCompleteRouteImport.update({
  id: '/_pages/beta-complete',
  path: '/beta-complete',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDocumentsIndexRoute = AppDocumentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDocumentsRoute,
} as any)
const AppDocumentsDocumentIdRoute = AppDocumentsDocumentIdRouteImport.update({
  id: '/$documentId',
  path: '/$documentId',
  getParentRoute: () => AppDocumentsRoute,
} as any)
const ApiAdminSearchDbRoute = ApiAdminSearchDbRouteImport.update({
  id: '/api/admin/search-db',
  path: '/api/admin/search-db',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLibraryDataRoute = ApiAdminLibraryDataRouteImport.update({
  id: '/api/admin/library-data',
  path: '/api/admin/library-data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminConfigurationRoute = ApiAdminConfigurationRouteImport.update({
  id: '/api/admin/configuration',
  path: '/api/admin/configuration',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/app': typeof AppRouteWithChildren
  '/beta-complete': typeof PagesBetaCompleteRoute
  '/cookie-error': typeof PagesCookieErrorRoute
  '/grant-denied': typeof PagesGrantDeniedRoute
  '/license': typeof PagesLicenseRoute
  '/safari-error': typeof PagesSafariErrorRoute
  '/api/configuration': typeof ApiConfigurationRoute
  '/api/library-data': typeof ApiLibraryDataRoute
  '/api/search-db': typeof ApiSearchDbRoute
  '/app/documents': typeof AppDocumentsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/api/admin/configuration': typeof ApiAdminConfigurationRoute
  '/api/admin/library-data': typeof ApiAdminLibraryDataRoute
  '/api/admin/search-db': typeof ApiAdminSearchDbRoute
  '/app/documents/$documentId': typeof AppDocumentsDocumentIdRoute
  '/app/documents/': typeof AppDocumentsIndexRoute
}
export interface FileRoutesByTo {
  '/app': typeof AppRouteWithChildren
  '/beta-complete': typeof PagesBetaCompleteRoute
  '/cookie-error': typeof PagesCookieErrorRoute
  '/grant-denied': typeof PagesGrantDeniedRoute
  '/license': typeof PagesLicenseRoute
  '/safari-error': typeof PagesSafariErrorRoute
  '/api/configuration': typeof ApiConfigurationRoute
  '/api/library-data': typeof ApiLibraryDataRoute
  '/api/search-db': typeof ApiSearchDbRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/api/admin/configuration': typeof ApiAdminConfigurationRoute
  '/api/admin/library-data': typeof ApiAdminLibraryDataRoute
  '/api/admin/search-db': typeof ApiAdminSearchDbRoute
  '/app/documents/$documentId': typeof AppDocumentsDocumentIdRoute
  '/app/documents': typeof AppDocumentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/app': typeof AppRouteWithChildren
  '/_pages/beta-complete': typeof PagesBetaCompleteRoute
  '/_pages/cookie-error': typeof PagesCookieErrorRoute
  '/_pages/grant-denied': typeof PagesGrantDeniedRoute
  '/_pages/license': typeof PagesLicenseRoute
  '/_pages/safari-error': typeof PagesSafariErrorRoute
  '/api/configuration': typeof ApiConfigurationRoute
  '/api/library-data': typeof ApiLibraryDataRoute
  '/api/search-db': typeof ApiSearchDbRoute
  '/app/documents': typeof AppDocumentsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/api/admin/configuration': typeof ApiAdminConfigurationRoute
  '/api/admin/library-data': typeof ApiAdminLibraryDataRoute
  '/api/admin/search-db': typeof ApiAdminSearchDbRoute
  '/app/documents/$documentId': typeof AppDocumentsDocumentIdRoute
  '/app/documents/': typeof AppDocumentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/app'
    | '/beta-complete'
    | '/cookie-error'
    | '/grant-denied'
    | '/license'
    | '/safari-error'
    | '/api/configuration'
    | '/api/library-data'
    | '/api/search-db'
    | '/app/documents'
    | '/auth/callback'
    | '/auth/sign-in'
    | '/api/admin/configuration'
    | '/api/admin/library-data'
    | '/api/admin/search-db'
    | '/app/documents/$documentId'
    | '/app/documents/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/app'
    | '/beta-complete'
    | '/cookie-error'
    | '/grant-denied'
    | '/license'
    | '/safari-error'
    | '/api/configuration'
    | '/api/library-data'
    | '/api/search-db'
    | '/auth/callback'
    | '/auth/sign-in'
    | '/api/admin/configuration'
    | '/api/admin/library-data'
    | '/api/admin/search-db'
    | '/app/documents/$documentId'
    | '/app/documents'
  id:
    | '__root__'
    | '/app'
    | '/_pages/beta-complete'
    | '/_pages/cookie-error'
    | '/_pages/grant-denied'
    | '/_pages/license'
    | '/_pages/safari-error'
    | '/api/configuration'
    | '/api/library-data'
    | '/api/search-db'
    | '/app/documents'
    | '/auth/callback'
    | '/auth/sign-in'
    | '/api/admin/configuration'
    | '/api/admin/library-data'
    | '/api/admin/search-db'
    | '/app/documents/$documentId'
    | '/app/documents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  PagesBetaCompleteRoute: typeof PagesBetaCompleteRoute
  PagesCookieErrorRoute: typeof PagesCookieErrorRoute
  PagesGrantDeniedRoute: typeof PagesGrantDeniedRoute
  PagesLicenseRoute: typeof PagesLicenseRoute
  PagesSafariErrorRoute: typeof PagesSafariErrorRoute
  ApiConfigurationRoute: typeof ApiConfigurationRoute
  ApiLibraryDataRoute: typeof ApiLibraryDataRoute
  ApiSearchDbRoute: typeof ApiSearchDbRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthSignInRoute: typeof AuthSignInRoute
  ApiAdminConfigurationRoute: typeof ApiAdminConfigurationRoute
  ApiAdminLibraryDataRoute: typeof ApiAdminLibraryDataRoute
  ApiAdminSearchDbRoute: typeof ApiAdminSearchDbRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/documents': {
      id: '/app/documents'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/search-db': {
      id: '/api/search-db'
      path: '/api/search-db'
      fullPath: '/api/search-db'
      preLoaderRoute: typeof ApiSearchDbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/library-data': {
      id: '/api/library-data'
      path: '/api/library-data'
      fullPath: '/api/library-data'
      preLoaderRoute: typeof ApiLibraryDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/configuration': {
      id: '/api/configuration'
      path: '/api/configuration'
      fullPath: '/api/configuration'
      preLoaderRoute: typeof ApiConfigurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pages/safari-error': {
      id: '/_pages/safari-error'
      path: '/safari-error'
      fullPath: '/safari-error'
      preLoaderRoute: typeof PagesSafariErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pages/license': {
      id: '/_pages/license'
      path: '/license'
      fullPath: '/license'
      preLoaderRoute: typeof PagesLicenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pages/grant-denied': {
      id: '/_pages/grant-denied'
      path: '/grant-denied'
      fullPath: '/grant-denied'
      preLoaderRoute: typeof PagesGrantDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pages/cookie-error': {
      id: '/_pages/cookie-error'
      path: '/cookie-error'
      fullPath: '/cookie-error'
      preLoaderRoute: typeof PagesCookieErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pages/beta-complete': {
      id: '/_pages/beta-complete'
      path: '/beta-complete'
      fullPath: '/beta-complete'
      preLoaderRoute: typeof PagesBetaCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/documents/': {
      id: '/app/documents/'
      path: '/'
      fullPath: '/app/documents/'
      preLoaderRoute: typeof AppDocumentsIndexRouteImport
      parentRoute: typeof AppDocumentsRoute
    }
    '/app/documents/$documentId': {
      id: '/app/documents/$documentId'
      path: '/$documentId'
      fullPath: '/app/documents/$documentId'
      preLoaderRoute: typeof AppDocumentsDocumentIdRouteImport
      parentRoute: typeof AppDocumentsRoute
    }
    '/api/admin/search-db': {
      id: '/api/admin/search-db'
      path: '/api/admin/search-db'
      fullPath: '/api/admin/search-db'
      preLoaderRoute: typeof ApiAdminSearchDbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/library-data': {
      id: '/api/admin/library-data'
      path: '/api/admin/library-data'
      fullPath: '/api/admin/library-data'
      preLoaderRoute: typeof ApiAdminLibraryDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/configuration': {
      id: '/api/admin/configuration'
      path: '/api/admin/configuration'
      fullPath: '/api/admin/configuration'
      preLoaderRoute: typeof ApiAdminConfigurationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppDocumentsRouteChildren {
  AppDocumentsDocumentIdRoute: typeof AppDocumentsDocumentIdRoute
  AppDocumentsIndexRoute: typeof AppDocumentsIndexRoute
}

const AppDocumentsRouteChildren: AppDocumentsRouteChildren = {
  AppDocumentsDocumentIdRoute: AppDocumentsDocumentIdRoute,
  AppDocumentsIndexRoute: AppDocumentsIndexRoute,
}

const AppDocumentsRouteWithChildren = AppDocumentsRoute._addFileChildren(
  AppDocumentsRouteChildren,
)

interface AppRouteChildren {
  AppDocumentsRoute: typeof AppDocumentsRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppDocumentsRoute: AppDocumentsRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  PagesBetaCompleteRoute: PagesBetaCompleteRoute,
  PagesCookieErrorRoute: PagesCookieErrorRoute,
  PagesGrantDeniedRoute: PagesGrantDeniedRoute,
  PagesLicenseRoute: PagesLicenseRoute,
  PagesSafariErrorRoute: PagesSafariErrorRoute,
  ApiConfigurationRoute: ApiConfigurationRoute,
  ApiLibraryDataRoute: ApiLibraryDataRoute,
  ApiSearchDbRoute: ApiSearchDbRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthSignInRoute: AuthSignInRoute,
  ApiAdminConfigurationRoute: ApiAdminConfigurationRoute,
  ApiAdminLibraryDataRoute: ApiAdminLibraryDataRoute,
  ApiAdminSearchDbRoute: ApiAdminSearchDbRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
