/**
 * Friendly aliases for the Onshape configuration types generated by
 * @hey-api/openapi-ts (see `openapi-ts.config.ts` and `../generated`).
 *
 * Regenerate the underlying `../generated` output with `npm run gen:onshape-types`;
 * keep these aliases in sync if the upstream schema names change.
 */
export type {
    // GET /configuration response.
    BtConfigurationResponse2019 as OnshapeConfigurationResponse,
    // Discriminated union of the four configuration parameter kinds.
    OnshapeConfigurationParameter,
    BtmConfigurationParameterEnum105 as OnshapeEnumParameter,
    BtmConfigurationParameterBoolean2550 as OnshapeBooleanParameter,
    BtmConfigurationParameterString872 as OnshapeStringParameter,
    BtmConfigurationParameterQuantity1826 as OnshapeQuantityParameter,
    BtmEnumOption592 as OnshapeEnumOption,
    BtQuantityRange181 as OnshapeQuantityRange,
    // Parameter / enum-option visibility conditions.
    OnshapeVisibilityCondition,
    OnshapeEnumOptionVisibilityCondition,
    BtEnumOptionVisibilityConditionList2936 as OnshapeEnumOptionVisibilityConditionList,
    // GET /configurationencodings/{cid} response.
    BtConfigurationInfo as OnshapeConfigurationInfo
} from "../generated";
